re-org scripts/readme/makefile

diff --git a/scripts/clonedetect/configure b/scripts/clonedetect/configure
--- a/scripts/clonedetect/configure
+++ b/scripts/clonedetect/configure
@@ -4,12 +4,12 @@ check_or_create_dir()
 {
   if [[ ! -d "${!1}" ]]; then
   if [[ -e "${!1}" ]]; then
-    echo "Error: $1 should be a directory"
+    echo "Error: $1 should be a directory. Check your config"
     exit 1
   else
     mkdir "${!1}"
     if [[ $? -ne 0 ]]; then
-      echo "Error: $1 doesn't exist and cannot be created"
+      echo "Error: $1 doesn't exist and cannot be created. Check your config"
       exit 1
     fi
   fi
@@ -19,7 +19,7 @@ fi
 check_file()
 {
 	if [[ ! -f $1 ]]; then
-		echo "Error: missing file $1"
+		echo "Error: missing file $1. Check your config"
 		exit 1
 	fi
 }
@@ -28,21 +28,32 @@ check_var()
 {
 	if [[ -z ${!1} ]];
 	then
-		echo "no $1 in config file"
+		echo "Error: $1 not set in config. Check your config"
 		exit 1
 	fi
 
 	export $1
 }
 
+check_exe()
+{
+	if (which "$1" >& /dev/null); then
+		return 0
+	else
+		echo "Error: missing required program: $1"
+		exit 1
+	fi
+}
+
 if [[ -e config ]];
 then
 	. config
 else
-	echo "no config file in current directory"
+	echo "Error: no config file in current directory"
 	exit 0
 fi
 
+check_var "DECKARD_DIR"
 check_var "FILE_PATTERN"
 check_var "SRC_DIR"
 
@@ -59,6 +70,8 @@ check_var "GROUPING_EXEC"
 check_file "$GROUPING_EXEC"
 check_var "CLUSTER_EXEC"
 check_file "$CLUSTER_EXEC"
+check_var "POSTPRO_EXEC"
+check_file "$POSTPRO_EXEC"
 
 check_var "MIN_TOKENS"
 check_var "STRIDE"
@@ -67,4 +80,14 @@ check_var "SIMILARITY"
 check_var "GROUPING_S"
 #check_var "GROUPING_D"
 #check_var "GROUPING_C"
+
+check_exe "which"
+check_exe "python"
+check_exe "awk"
+check_exe "sed"
+check_exe "grep"
+check_exe "find"
+check_exe "bash"
+check_exe "cat"
+check_exe "touch"
 
