re-org scripts plus bug fixes

diff --git a/scripts/clonedetect/vertical-param-batch b/scripts/clonedetect/vertical-param-batch
--- a/scripts/clonedetect/vertical-param-batch
+++ b/scripts/clonedetect/vertical-param-batch
@@ -23,17 +23,20 @@ clean()
       echo -n "...deleting cluster_vdb_*_*_g*_*_* ..."
       find "$CLUSTER_DIR" -type f -name "cluster_vdb_*_*_g[0-9]*_*_*" -print0 | xargs -0 -r --max-args=500 rm -f
       echo "Done"
-      echo -n "...deleting cluster_vdb_*_*_allg_*_* ..."
-      find "$CLUSTER_DIR" -type f -name "cluster_vdb_*_*_allg_*_*" -print0 | xargs -0 -r rm -f
-      echo "Done"
 }
 
 # Delete log files and result files: if no argv, delete all files
 clean_log()
 {
-	echo "Cleaning up all result and log files..."
+	echo "Cleaning up all results and log files..."
+	echo -n "...deleting cluster_vdb_*_*_allg_*_* ..."
+	find "$CLUSTER_DIR" -type f -name "cluster_vdb_*_*_allg_*_*" -print0 | xargs -0 -r rm -f
+	echo "Done"
 	echo -n "...deleting post_cluster_vdb_*_*_allg_*_* ..."
 	find "$CLUSTER_DIR" -type f -name "post_cluster_vdb_*_*_allg_*_*" -print0 | xargs -0 -r rm -f
+	echo "Done"
+	echo -n "...deleting ranges_*_* ..."
+	find "$VECTOR_DIR" -type f -name "ranges_*_*" -print0 | xargs -0 -r rm -f
 	echo "Done"
 	echo -n "...deleting logs..."
 	find "$TIME_DIR" -type f -name "grouping_*" -print0 | xargs -0 -r --max-args=500 rm -f 
@@ -46,30 +49,43 @@ clean_log()
 }
 
 # vector grouping: $1=<token size>, $2=<stride>, $3=<distance>
+# group file names generated by rundispatchonefile: $VECTOR_DIR/vdb_$1_$2_g<gid>_$3_${GROUPING_S}_${GROUPING_H}
 grouping()
 {
-    echo -n "$FUNCNAME: $VECTOR_DIR/vdb_$1_$2 with distance=$3..."
-    if [[ "$TOOVERWRITE"!="true" &&
-	  -s "$VECTOR_DIR/vdb_$1_$2_g0_$3_${GROUPING_S}" &&
-	  "$VECTOR_DIR/vdb_$1_$2_g0_$3_${GROUPING_S}" -nt "$VECTOR_DIR/vdb_$1_$2" ]];
-    then
-	echo "Warning: $VECTOR_DIR/vdb_$1_$2 has already been grouped for distance=$3 and starting range ${GROUPING_S}. Delete them manually or use '$0 overwrite'."
-	echo "$FUNCNAME: $1 $2 $3 ...Skip."
-	return 0
-    else
+    echo -n "$FUNCNAME: $VECTOR_DIR/vdb_$1_$2 with distance=$3..." | tee -a "$TIME_DIR/grouping_$1_$2_$3_${GROUPING_S}"
+    # note for bash: must have the space before and after '!=' to make it work correctly; otherwise, silent errors.
+    if [[ "$TOOVERWRITE" != "true" ]]; then
+	togroup=
+	grpnumber=`find "$VECTOR_DIR" -type f -regex ".*vdb_$1_$2_g[0-9]+_$3_${GROUPING_S}.*" | wc -l`
+	if [[ $grpnumber -le 0 ]]; then
+		togroup="true"
+	else
+	    while read grpf; do
+		if [[ ! -s "$grpf" || "$grpf" -ot "$VECTOR_DIR/vdb_$1_$2" ]]; then
+			togroup="true"
+			break
+		fi
+	    done < <( find "$VECTOR_DIR" -regex ".*vdb_$1_$2_g[0-9]+_$3_${GROUPING_S}.*" )
+        fi
+	if [[ "$togroup" != "true" ]]; then
+		echo "Warning: $VECTOR_DIR/vdb_$1_$2 has already been grouped for distance=$3 and starting range ${GROUPING_S}. Delete $VECTOR_DIR/vdb_$1_$2_g[0-9]* manually or use '$0 overwrite'." | tee -a "$TIME_DIR/grouping_$1_$2_$3_${GROUPING_S}"
+		echo "$FUNCNAME: $1 $2 $3 ...Skip." | tee -a "$TIME_DIR/grouping_$1_$2_$3_${GROUPING_S}"
+		return 0
+	fi
+    fi
+
 	# delete old vector groups, in case some files may not be overwritten:
-	find "$VECTOR_DIR/" -regex ".*vdb_$1_$2_g[0-9]+_$3_${GROUPING_S}" -print0 | xargs -0 -r --max-args=500 rm -f
+	find "$VECTOR_DIR/" -regex ".*vdb_$1_$2_g[0-9]+_$3_${GROUPING_S}.*" -print0 | xargs -0 -r --max-args=500 rm -f
 	( time \
-          "`dirname ${GROUPING_EXEC}`/rundispatchonefile" "$VECTOR_DIR/vdb_$1_$2" $3 -l $GROUPING_S -h $GROUPING_H -o "$VECTOR_DIR" -p "vdb_$1_$2" || (echo "Error: $FUNCNAME failure: $1 $2 $3"; exit 1)
-	) >& "$TIME_DIR/grouping_$1_$2_$3_${GROUPING_S}"
+          "`dirname ${GROUPING_EXEC}`/rundispatchonefile" "$VECTOR_DIR/vdb_$1_$2" $3 -l $GROUPING_S -h $GROUPING_H -o "$VECTOR_DIR" -p "vdb_$1_$2" || (echo "Error: $FUNCNAME failure: $1 $2 $3"; exit 1) \
+	) 1>>"$TIME_DIR/grouping_$1_$2_$3_${GROUPING_S}" 2>&1
 	errcode=$?
 	if [[ $errcode -ne 0 ]]; then
-		echo "$FUNCNAME: Possible errors occurred. Check log: $TIME_DIR/grouping_$1_$2_$3_${GROUPING_S}"
+		echo "$FUNCNAME: Possible errors occurred. Check log: $TIME_DIR/grouping_$1_$2_$3_${GROUPING_S}" | tee -a "$TIME_DIR/grouping_$1_$2_$3_${GROUPING_S}"
 	else
-		echo "Done $FUNCNAME $1 $2 $3. See groups in $VECTOR_DIR/vdb_$1_$2_g[0-9]*_$3_${GROUPING_S}"
+		echo "Done $FUNCNAME $1 $2 $3. See groups in $VECTOR_DIR/vdb_$1_$2_g[0-9]*_$3_${GROUPING_S}*" | tee -a "$TIME_DIR/grouping_$1_$2_$3_${GROUPING_S}"
 	fi
 	return $errcode
-    fi
 }
 
 # set parameter files: $1=<token size>, $2=<stride>, $3=<sim>
@@ -78,26 +94,26 @@ paramsetting()
     t=$1
     s=$2
     sim=$3
-    echo -n "paramsetting: $t $s $sim ..."
+    echo -n "paramsetting: $t $s $sim ..." | tee -a "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
 # convert SIMILARITY to DISTANCE:
     i=`echo "$sim ${GROUPING_S}" | awk '{printf( "%.7g\n", sqrt((1-$1)*$2) )}'`
 # create the range file if not exist:
-    if [[ "$TOOVERWRITE"="true" || ! -s "${VECTOR_DIR}/ranges_${i}_${GROUPING_S}*" ]]; then
+    if [[ "$TOOVERWRITE" = "true" || ! -s "${VECTOR_DIR}/ranges_${i}_${GROUPING_S}" ]]; then
         "`dirname $GROUPING_EXEC`/computeranges" $i $GROUPING_S $GROUPING_H > "${VECTOR_DIR}/ranges_${i}_${GROUPING_S}"
     fi
     if [[ ! -s "${VECTOR_DIR}/ranges_${i}_${GROUPING_S}" ]]; then
-        echo "Error: $FUNCNAME failure: Can't generate the range file: ranges_${i}_${GROUPING_S}"
+        echo "Error: $FUNCNAME failure: Can't generate the range file: ranges_${i}_${GROUPING_S}" | tee -a "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
         exit 87
     fi
 # use the largest group file for paramter tuning:
 # "head -n 1" may break the pipe coming from "ls", causing signal 13 (no more reader, while writer's still writing), but should not matter here:
-    groupfortuning=`find $VECTOR_DIR -type f -name "vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}" -not -name '*.param' -print0 | xargs -0 ls -S | head -n 1`
-    grptuningid=`echo ${groupfortuning} | sed "s/.*vdb_${t}_${s}_g\([0-9]*\)_${i}_${GROUPING_S}/\1/"`
+    groupfortuning=`find $VECTOR_DIR -type f -name "vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}*" -not -name '*.param' -print0 | xargs -0 ls -S | head -n 1`
+    grptuningid=`echo ${groupfortuning} | sed "s/.*vdb_${t}_${s}_g\([0-9]*\)_${i}_${GROUPING_S}.*/\1/"`
     grpal=0
     grpdist=0
 # if $grptuningid is empty, error occurs...
     if [[ $grptuningid -le 0 ]]; then
-        echo "Error: $FUNCNAME: invalid group id: $grptuningid: $t $s $sim $i"
+        echo "Error: $FUNCNAME: invalid group id: $grptuningid: $t $s $sim $i" | tee -a "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
         exit 127
     elif [[ $grptuningid -eq 1 ]]; then
 	grpal=`head -n $(expr $grptuningid + 1) ${VECTOR_DIR}/ranges_${i}_${GROUPING_S} | tail -n 1 | awk '{print $3}'`
@@ -106,20 +122,22 @@ paramsetting()
 	grpal=`head -n $(expr $grptuningid + 1) ${VECTOR_DIR}/ranges_${i}_${GROUPING_S} | tail -n 1 | awk '{print $2}'`
 	grpdist=`echo "$sim ${grpal}" | awk '{printf( "%.7g\n", sqrt((1-$1)*2*$2) )}'`
     fi
-    echo -n "Looking for optimal parameters by "
-    cluster $groupfortuning $grpdist -c  # TODO: to write to some log file?
+    echo -n "Looking for optimal parameters by " | tee -a "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
+    cluster $groupfortuning $grpdist -c | tee -a "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
     errcode=$?
 
     if [[ $errcode -ne 0 || ! -s "${groupfortuning}.param" ]]; then
-	echo "Error: $FUNCNAME failure...exit."
+	echo "Error: $FUNCNAME failure...exit." | tee -a "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
 	exit 3
     fi
 
-    echo -n "Setting Parameters for all other groups..."
+    echo -n "Setting Parameters for all other groups (may take hours on cygwin but only minutes on Linux...why?)..." | tee -a "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
+    # TODO: performance improvements to reduce file I/O; replace head/tail/awk/generateparam
     ( time \
-	find "$VECTOR_DIR" -type f -name "vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}" -not -name '*.param' | while read vdb;
+	find "$VECTOR_DIR" -type f -name "vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}*" -not -name '*.param' | while read vdb;
 	do
-	grpfileid=`echo "$vdb" | sed "s/.*vdb_${t}_${s}_g\([0-9]*\)_${i}_${GROUPING_S}/\1/"`
+		echo "vdb: '$vdb'"
+	grpfileid=`echo "$vdb" | sed "s/.*vdb_${t}_${s}_g\([0-9]*\)_${i}_${GROUPING_S}.*/\1/"`
 	grpal=0
 	grpdist=0
 	if [[ ${grptuningid} -eq $grpfileid ]]; then
@@ -134,14 +152,14 @@ paramsetting()
 	lineno=`wc -l "$vdb" | awk '{print $1}'`
 	lineno=$(($lineno / 2))
 	"`dirname $0`/generateparam" "${groupfortuning}.param" $lineno $grpdist > "${vdb}.param"
-	done
-    ) >& "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
+	done \
+    ) 1>>"${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}" 2>&1
     errcode=$?
 
     if [[ $errcode -ne 0 ]]; then
-	    echo "$FUNCNAME: Possible errors occurred. Check log: $TIME_DIR/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
+	    echo "$FUNCNAME: Possible errors occurred. Check log: $TIME_DIR/paramsetting_${t}_${s}_${sim}_${GROUPING_S}" | tee -a "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
     else
-	    echo "Done $FUNCNAME $t $s $sim. Log: $TIME_DIR/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
+	    echo "Done $FUNCNAME $t $s $sim. Log: $TIME_DIR/paramsetting_${t}_${s}_${sim}_${GROUPING_S}" | tee -a "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
     fi
     return $errcode
 }
@@ -158,13 +176,13 @@ cluster()
 	    flag=
 	fi
 
-	echo -n "Clustering '${vdb}' ${grpdist} ..."
+	echo -n "Clustering '${vdb}' ${grpdist} ..." | tee -a "$TIME_DIR/cluster_${vfile}"
 
-	if [[ "$TOOVERWRITE"!="true" &&
+	if [[ "$TOOVERWRITE" != "true" &&
 	      -s "$CLUSTER_DIR/cluster_${vfile}_$2" &&
 	      "$CLUSTER_DIR/cluster_${vfile}_$2" -nt "$vdb" ]];
         then
-		echo "Warning: $CLUSTER_DIR/cluster_${vfile}_$2 exists...Skip."
+		echo "Warning: $CLUSTER_DIR/cluster_${vfile}_$2 exists...Skip." | tee -a "$TIME_DIR/cluster_${vfile}"
 		return 0
 	fi
 
@@ -191,26 +209,26 @@ cluster()
 	elif [ $mem -lt 2048 ]; then
 		mem=3800000000
 	else
-		echo "Error: Size of $vdb > 2G. I don't want to do it before you think of any optimization."
+		echo "Error: Size of $vdb > 2G. I don't want to do it before you think of any optimization." | tee -a "$TIME_DIR/cluster_${vfile}"
 		exit 1;
 	fi
 
 	# group vector files should have already <dist> in their names; parameter files should also exist:
 	if [[ $3 != "-c" && -s "${vdb}" &&
 	      ! -s "${vdb}.param" ]]; then
-		echo "Error: Parameter File missing for '$vdb' $dist...Exit"
+		echo "Error: Parameter File missing for '$vdb' $dist...Exit" | tee -a "$TIME_DIR/cluster_${vfile}"
 		exit 65
 	fi
 	( time \
 	  "$CLUSTER_EXEC" -R $dist -M $mem -b 2 -A -f "$vdb" ${flag} -p "${vdb}.param" \
 	  > "$CLUSTER_DIR/cluster_${vfile}" \
-	) >& "$TIME_DIR/cluster_${vfile}"
+	) 1>>"$TIME_DIR/cluster_${vfile}" 2>&1
 	errcode=$?
 
 	if [[ $errcode -ne 0 ]]; then
-		echo "$FUNCNAME: Possible errors occurred. Check log: $TIME_DIR/cluster_${vfile}"
+		echo "$FUNCNAME: Possible errors occurred. Check log: $TIME_DIR/cluster_${vfile}" | tee -a "$TIME_DIR/cluster_${vfile}"
 	else
-		echo "Done clustering '${vdb}' ${grpdist}. Log: $TIME_DIR/cluster_${vfile}"
+		echo "Done clustering '${vdb}' ${grpdist}. Log: $TIME_DIR/cluster_${vfile}" | tee -a "$TIME_DIR/cluster_${vfile}"
 	fi
 	return $errcode
 }
@@ -226,28 +244,28 @@ pcluster()
 #          "$coverage" "$cdb" > "${CLUSTER_DIR}/coverage_${cfile}" \
 #        ) >& "${TIME_DIR}/coverage_${cfile}"
 # Post-processing:
-	echo -n "Post processing $cdb ..."
+	echo -n "Post processing $cdb ..." | tee -a "${TIME_DIR}/post_${cfile}"
 	if [[ $(wc -l "$cdb" | awk '{print $1}') -lt 2 ]];
 	then
-		echo "Warning: clone cluster file is too small to be right: $cdb...Skip."
+		echo "Warning: clone cluster file is too small to be right: $cdb...Skip." | tee -a "${TIME_DIR}/post_${cfile}"
 		return 1
 	fi
 
-	if [[ "$TOOVERWRITE"!="true" &&
+	if [[ "$TOOVERWRITE" != "true" &&
 	      -s "$CLUSTER_DIR/post_${cfile}" &&
 	      "$CLUSTER_DIR/post_${cfile}" -nt "$cdb" ]];
         then
-		echo "Warning: $CLUSTER_DIR/post_${cfile} exists...Skip. May manually delete it or set 'overwrite'"
+		echo "Warning: $CLUSTER_DIR/post_${cfile} exists...Skip. May manually delete it or set 'overwrite'" | tee -a "${TIME_DIR}/post_${cfile}"
 		return 0
 	else
 		( time \
-		  "$POSTPRO_EXEC" "$cdb" > "${CLUSTER_DIR}/post_${cfile}"
-		) >& "${TIME_DIR}/post_${cfile}"
+		  "$POSTPRO_EXEC" "$cdb" > "${CLUSTER_DIR}/post_${cfile}" \
+		) 1>>"${TIME_DIR}/post_${cfile}" 2>&1
 		errcode=$?
 		if [[ $errcode -ne 0 ]]; then
-			echo "$FUNCNAME: Possible errors occurred. Check log: $TIME_DIR/post_${cfile}"
+			echo "$FUNCNAME: Possible errors occurred. Check log: $TIME_DIR/post_${cfile}" | tee -a "${TIME_DIR}/post_${cfile}"
 		else
-			echo "Done post-processing $cdb. Log: $TIME_DIR/post_${cfile}"
+			echo "Done post-processing $cdb. Log: $TIME_DIR/post_${cfile}" | tee -a "${TIME_DIR}/post_${cfile}"
 		fi
 		return $errcode
 	fi
@@ -307,14 +325,14 @@ do
 	paramsetting $t $s $sim
 	errcode=$?
 # Clustering:
-	find "$VECTOR_DIR" -type f -name "vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}" -not -name '*.param' | while read vdb;
+	find "$VECTOR_DIR" -type f -name "vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}*" -not -name '*.param' | while read vdb;
 	do
-	  grpfileid=`echo "$vdb" | sed "s/.*vdb_${t}_${s}_g\([0-9]*\)_${i}_${GROUPING_S}/\1/"`
+	  grpfileid=`echo "$vdb" | sed "s/.*vdb_${t}_${s}_g\([0-9]*\)_${i}_${GROUPING_S}.*/\1/"`
 	  grpal=0
 	  grpdist=0
 	  # TODO: what are better distance parameters for the groups?
           if [[ $grpfileid -le 0 ]]; then
-              echo "Warning: invalid group id: $grpfileid in group $vdb...Skip."
+              echo "Warning: invalid group id: $grpfileid in group $vdb...Skip." | tee -a "$TIME_DIR/cluster_vdb_${t}_${s}_allg_${i}_${GROUPING_S}"
               continue
 	  elif [[ $grpfileid -eq 1 ]]; then
 		grpal=`head -n $(expr $grpfileid + 1) $(dirname "$vdb")/ranges_${i}_${GROUPING_S} | tail -n 1 | awk '{print $3}'`
@@ -323,32 +341,42 @@ do
 		grpal=`head -n $(expr $grpfileid + 1) $(dirname "$vdb")/ranges_${i}_${GROUPING_S} | tail -n 1 | awk '{print $2}'`
 	  	grpdist=`echo "$sim ${grpal}" | awk '{printf( "%.7g\n", sqrt((1-$1)*2*$2) )}'`
 	  fi
-	  cluster "$vdb" $grpdist
+	  cluster "$vdb" $grpdist 1>>"$TIME_DIR/cluster_vdb_${t}_${s}_allg_${i}_${GROUPING_S}" 2>&1
 	  errcode=$?
 	done
 # Merging:
-	echo -n "Merging all clone reports into $CLUSTER_DIR/cluster_vdb_${t}_${s}_allg_${sim}_${GROUPING_S} ..."
-	if [[ "$TOOVERWRITE"!="true" &&
-	      -s "$CLUSTER_DIR/cluster_vdb_${t}_${s}_allg_${sim}_${GROUPING_S}" &&
-	      "$CLUSTER_DIR/cluster_vdb_${t}_${s}_allg_${sim}_${GROUPING_S}" -nt "$CLUSTER_DIR/cluster_vdb_${t}_${s}_g0_${i}_${GROUPING_S}" ]];
-	then
-		echo "Warning: '$CLUSTER_DIR/cluster_vdb_${t}_${s}_allg_${sim}_${GROUPING_S}' exists...Skip."
+	echo -n "Merging all clone reports into $CLUSTER_DIR/cluster_vdb_${t}_${s}_allg_${sim}_${GROUPING_S} ..." | tee -a "$TIME_DIR/merging_${t}_${s}_${sim}_${GROUPING_S}"
+	tomerge=
+	if [[ "$TOOVERWRITE" = "true" ]]; then
+		tomerge="true"
+	elif [[ ! -s "$CLUSTER_DIR/cluster_vdb_${t}_${s}_allg_${sim}_${GROUPING_S}" ]]; then
+		tomerge="true"
+	else
+		while read grpf; do
+			if [[ "$CLUSTER_DIR/cluster_vdb_${t}_${s}_allg_${sim}_${GROUPING_S}" -ot "$grpf" ]]; then
+				tomerge="true"
+				break
+			fi
+		done < <( find "$CLUSTER_DIR" -type f -name "cluster_vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}*" )
+	fi
+	if [[ "$tomerge" != "true" ]]; then
+		echo "Warning: '$CLUSTER_DIR/cluster_vdb_${t}_${s}_allg_${sim}_${GROUPING_S}' exists...Skip." | tee -a "$TIME_DIR/merging_${t}_${s}_${sim}_${GROUPING_S}"
 	else
 		# Continue to merge:
 		echo -n > "$CLUSTER_DIR/cluster_vdb_${t}_${s}_allg_${sim}_${GROUPING_S}"
 		( time \
-		  find "$CLUSTER_DIR" -type f -name "cluster_vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}" | while read grpf;
+		  find "$CLUSTER_DIR" -type f -name "cluster_vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}*" | while read grpf;
 		  do
 			# remove some output lines in each file outputted by LSH/enumBuckets:
 			lineno=`wc -l $grpf | awk '{print $1;}'`
 			head -n `expr $lineno - 2` $grpf | tail -n `expr $lineno - 11` >> "$CLUSTER_DIR/cluster_vdb_${t}_${s}_allg_${sim}_${GROUPING_S}"
 		  done \
-		) >& "${TIME_DIR}/merging_${t}_${s}_${sim}_${GROUPING_S}"
+		) 1>>"${TIME_DIR}/merging_${t}_${s}_${sim}_${GROUPING_S}" 2>&1
 		errcode=$?
 		if [[ $errcode -ne 0 ]]; then
-			echo "Merging: Possible errors occurred. Check log: $TIME_DIR/merging_${t}_${s}_${sim}_${GROUPING_S}"
+			echo "Merging: Possible errors occurred. Check log: $TIME_DIR/merging_${t}_${s}_${sim}_${GROUPING_S}" | tee -a "$TIME_DIR/merging_${t}_${s}_${sim}_${GROUPING_S}"
 		else
-			echo "Done merging $CLUSTER_DIR/cluster_vdb_${t}_${s}_all_${sim}_${GROUPING_S}. Log: $TIME_DIR/merging_${t}_${s}_${sim}_${GROUPING_S}"
+			echo "Done merging $CLUSTER_DIR/cluster_vdb_${t}_${s}_all_${sim}_${GROUPING_S}. Log: $TIME_DIR/merging_${t}_${s}_${sim}_${GROUPING_S}" | tee -a "$TIME_DIR/merging_${t}_${s}_${sim}_${GROUPING_S}"
 		fi
 	fi
 # Post-processing:
