Make Deckard run faster on a multi-core machine by parallelized execution of various components in Deckard.

diff --git a/scripts/clonedetect/vertical-param-batch b/scripts/clonedetect/vertical-param-batch
--- a/scripts/clonedetect/vertical-param-batch
+++ b/scripts/clonedetect/vertical-param-batch
@@ -2,8 +2,8 @@
 
 #
 # 
-# Copyright (c) 2007-2012,
-#   Lingxiao Jiang         <lxjiang@ucdavis.edu>
+# Copyright (c) 2007-2013, University of California / Singapore Management University
+#   Lingxiao Jiang         <lxjiang@ucdavis.edu> <lxjiang@smu.edu.sg>
 #   Ghassan Misherghi      <ghassanm@ucdavis.edu>
 #   Zhendong Su            <su@ucdavis.edu>
 #   Stephane Glondu        <steph@glondu.net>
@@ -40,7 +40,8 @@
 # Feel free to adjust the workflows in the scripts to fit your needs.
 
 TOOVERWRITE=
-coverage=`dirname $0`/cd_coverage
+EXEC_DIR=`dirname $0`
+coverage=$EXEC_DIR/cd_coverage
 GROUPING_H=100000
 
 # Delete intermediate files, but leave times/*, cluster/coverage*, cluster/post_* files there:
@@ -127,7 +128,7 @@ paramsetting()
     t=$1
     s=$2
     sim=$3
-    echo -n "paramsetting: $t $s $sim ..." | tee -a "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
+    echo -n "paramsetting: $t $s $sim ..." | tee "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
 # convert SIMILARITY to DISTANCE:
     i=`echo "$sim ${GROUPING_S}" | awk '{printf( "%.7g\n", sqrt((1-$1)*$2) )}'`
 # create the range file if not exist:
@@ -140,6 +141,11 @@ paramsetting()
     fi
 # use the largest group file for paramter tuning:
 # "head -n 1" may break the pipe coming from "ls", causing signal 13 (no more reader, while writer's still writing), but should not matter here:
+    grptuningid=`find "$VECTOR_DIR" -type f -name "vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}*" -not -name '*.param' | wc -l`
+    if [[ $grptuningid -le 0 ]]; then
+	    echo "Error: $FUNCNAME failure: no vector group found: $t $s $sim" | tee -a "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
+	    exit 1
+    fi
     groupfortuning=`find "$VECTOR_DIR" -type f -name "vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}*" -not -name '*.param' -print0 | xargs -0 ls -S | head -n 1`
     grptuningid=`echo ${groupfortuning} | sed "s/.*vdb_${t}_${s}_g\([0-9]*\)_${i}_${GROUPING_S}.*/\1/"`
     grpal=0
@@ -156,7 +162,7 @@ paramsetting()
 	grpdist=`echo "$sim ${grpal}" | awk '{printf( "%.7g\n", sqrt((1-$1)*2*$2) )}'`
     fi
     echo -n "Looking for optimal parameters by " | tee -a "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
-    cluster $groupfortuning $grpdist -c | tee -a "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
+    cluster $groupfortuning $grpdist -c >> "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
     errcode=$?
 
     if [[ $errcode -ne 0 || ! -s "${groupfortuning}.param" ]]; then
@@ -167,25 +173,10 @@ paramsetting()
     echo -n "Setting Parameters for all other groups (may take hours on cygwin but only minutes on Linux...why?)..." | tee -a "${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}"
     # TODO: performance improvements to reduce file I/O; replace head/tail/awk/generateparam
     ( time \
-	find "$VECTOR_DIR" -type f -name "vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}*" -not -name '*.param' | while read vdb;
-	do
-		echo "$FUNCNAME: ${vdb}.param"
-		grpfileid=`echo "$vdb" | sed "s/.*vdb_${t}_${s}_g\([0-9]*\)_${i}_${GROUPING_S}.*/\1/"`
-		grpal=0
-		grpdist=0
-		if [[ ${grptuningid} -eq $grpfileid ]]; then
-			continue
-		elif [[ $grpfileid -eq 1 ]]; then
-			grpal=`head -n $(expr $grpfileid + 1) $(dirname "$vdb")/ranges_${i}_${GROUPING_S} | tail -n 1 | awk '{print $3}'`
-			grpdist=`echo "$sim ${grpal}" | awk '{printf( "%.7g\n", sqrt((1-$1)*$2) )}'`
-		else
-			grpal=`head -n $(expr $grpfileid + 1) $(dirname "$vdb")/ranges_${i}_${GROUPING_S} | tail -n 1 | awk '{print $2}'`
-			grpdist=`echo "$sim ${grpal}" | awk '{printf( "%.7g\n", sqrt((1-$1)*2*$2) )}'`
-		fi
-		lineno=`wc -l "$vdb" | awk '{print $1}'`
-		lineno=$(($lineno / 2))
-		"`dirname $0`/generateparam" "${groupfortuning}.param" $lineno $grpdist > "${vdb}.param"
-	done \
+#	find "$VECTOR_DIR" -type f -name "vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}*" -not -name '*.param' | while read vdb;
+#	do
+	find "$VECTOR_DIR" -type f -name "vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}*" -not -name '*.param' -print0 | xargs -0 -t -n 1 -P $MAX_PROCS "$EXEC_DIR/paramsetting_groupfile" $t $s $sim $groupfortuning
+#	done \
     ) 1>>"${TIME_DIR}/paramsetting_${t}_${s}_${sim}_${GROUPING_S}" 2>&1
     errcode=$?
 
@@ -209,7 +200,7 @@ cluster()
 	    flag=
 	fi
 
-	echo -n "Clustering '${vdb}' ${grpdist} ..." | tee -a "$TIME_DIR/cluster_${vfile}"
+	echo "Clustering '${vdb}' ${grpdist} ..." | tee -a "$TIME_DIR/cluster_${vfile}"
 
 	if [[ "$TOOVERWRITE" != "true" &&
 	      -s "$CLUSTER_DIR/cluster_${vfile}_$2" &&
@@ -252,6 +243,7 @@ cluster()
 		echo "Error: Parameter File missing for '$vdb' $dist...Exit" | tee -a "$TIME_DIR/cluster_${vfile}"
 		exit 65
 	fi
+	echo "$CLUSTER_EXEC" -R $dist -M $mem -b 2 -A -f "$vdb" ${flag} -p "${vdb}.param" " > " "$CLUSTER_DIR/cluster_${vfile}" | tee -a "$TIME_DIR/cluster_${vfile}"
 	( time \
 	  "$CLUSTER_EXEC" -R $dist -M $mem -b 2 -A -f "$vdb" ${flag} -p "${vdb}.param" \
 	  > "$CLUSTER_DIR/cluster_${vfile}" \
@@ -259,7 +251,7 @@ cluster()
 	errcode=$?
 
 	if [[ $errcode -ne 0 ]]; then
-		echo "$FUNCNAME: Possible errors occurred. Check log: $TIME_DIR/cluster_${vfile}" | tee -a "$TIME_DIR/cluster_${vfile}"
+		echo "$FUNCNAME: Possible errors occurred with LSH. Check log: $TIME_DIR/cluster_${vfile}" | tee -a "$TIME_DIR/cluster_${vfile}"
 	else
 		echo "Done clustering '${vdb}' ${grpdist}. Log: $TIME_DIR/cluster_${vfile}" | tee -a "$TIME_DIR/cluster_${vfile}"
 	fi
@@ -312,7 +304,7 @@ pcluster()
 }
 
 
-. `dirname $0`/configure
+. "$EXEC_DIR/configure"
 
 if [[ $# -ge 1 ]]; then
 	case "$1" in
@@ -342,7 +334,8 @@ do
   do
     for sim in $SIMILARITY;
     do
-	echo "Vector clustering w/ MIN_TOKENS=$t, STRIDE=$s, SIMILARITY=$sim ..."
+	echo
+	echo "= Vector clustering w/ MIN_TOKENS=$t, STRIDE=$s, SIMILARITY=$sim ..."
 	echo
 
 # convert SIMILARITY to DISTANCE used by LSH:
@@ -351,36 +344,27 @@ do
 # Grouping:
 	grouping $t $s $i
 	errcode=$?
+	if [[ $errcode -ne 0 ]]; then
+		echo "Error: grouping $t $s $sim. There may be no vectors or permission denied for the setting."
+		continue
+	fi
 	# NOTE:
 	#   range file name:  ranges_${i}_${GROUPING_S}
 	#   group file names: vdb_${t}_${s}_g[0-9]+_${i}_${GROUPING_S}
 # Set parameter files for LSH:
 	paramsetting $t $s $sim
 	errcode=$?
+	if [[ $errcode -ne 0 ]]; then
+		echo "Error: paramsetting $t $s $sim. There may be no vectors or permission denied for the setting."
+		continue
+	fi
 # Clustering:
 	echo "Cluster every vector groups..." | tee "$TIME_DIR/cluster_vdb_${t}_${s}_allg_${i}_${GROUPING_S}"
-	find "$VECTOR_DIR" -type f -name "vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}*" -not -name '*.param' | while read vdb;
-	do
-	  grpfileid=`echo "$vdb" | sed "s/.*vdb_${t}_${s}_g\([0-9]*\)_${i}_${GROUPING_S}.*/\1/"`
-	  grpal=0
-	  grpdist=0
-	  # TODO: what are better distance parameters for the groups?
-          if [[ $grpfileid -le 0 ]]; then
-              echo "Warning: invalid group id: $grpfileid in group $vdb...Skip." | tee -a "$TIME_DIR/cluster_vdb_${t}_${s}_allg_${i}_${GROUPING_S}"
-              continue
-	  elif [[ $grpfileid -eq 1 ]]; then
-		grpal=`head -n $(expr $grpfileid + 1) $(dirname "$vdb")/ranges_${i}_${GROUPING_S} | tail -n 1 | awk '{print $3}'`
-	  	grpdist=`echo "$sim ${grpal}" | awk '{printf( "%.7g\n", sqrt((1-$1)*$2) )}'`
-	  else
-		grpal=`head -n $(expr $grpfileid + 1) $(dirname "$vdb")/ranges_${i}_${GROUPING_S} | tail -n 1 | awk '{print $2}'`
-	  	grpdist=`echo "$sim ${grpal}" | awk '{printf( "%.7g\n", sqrt((1-$1)*2*$2) )}'`
-	  fi
-	  cluster "$vdb" $grpdist 1>>"$TIME_DIR/cluster_vdb_${t}_${s}_allg_${i}_${GROUPING_S}" 2>&1
-	  errcode=$?
-	  if [[ $errcode -ne 0 ]]; then
-		  echo "Clustering: Possible errors for vector group: $vdb $grpdist. Check log: $TIME_DIR/cluster_$(basename "${vdb}")" | tee -a "$TIME_DIR/cluster_vdb_${t}_${s}_allg_${i}_${GROUPING_S}"
-	  fi
-	done
+#	find "$VECTOR_DIR" -type f -name "vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}*" -not -name '*.param' | while read vdb;
+#	do
+   export -f cluster
+	find "$VECTOR_DIR" -type f -name "vdb_${t}_${s}_g[0-9]*_${i}_${GROUPING_S}*" -not -name '*.param' -print0 | xargs -0 -n 1 -P $MAX_PROCS "$EXEC_DIR/vdbclustergroup" $t $s $sim
+#	done
 	echo "Done clustering. Check log: $TIME_DIR/cluster_vdb_${t}_${s}_allg_${i}_${GROUPING_S} and $TIME_DIR/cluster_vdb_${t}_${s}_g[0-9]+_${i}_${GROUPING_S}" | tee -a "$TIME_DIR/cluster_vdb_${t}_${s}_allg_${i}_${GROUPING_S}"
 # Merging:
 	echo -n "Merging all clone reports into $CLUSTER_DIR/cluster_vdb_${t}_${s}_allg_${sim}_${GROUPING_S} ..." | tee -a "$TIME_DIR/merging_${t}_${s}_${sim}_${GROUPING_S}"
